version: "3.7"
services:
  # APP
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3111:3000"
      - "5111:5555"
    env_file: ./env/.env.app
    stdin_open: true
